// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCiaLm3PFoFIKVJwSva-pLorz1jQxWxesw',
    appId: '1:437672983587:web:c1b52abb7264f42e330596',
    messagingSenderId: '437672983587',
    projectId: 'pao-app-293f0',
    authDomain: 'pao-app-293f0.firebaseapp.com',
    storageBucket: 'pao-app-293f0.firebasestorage.app',
    measurementId: 'G-4NGYZCR878',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUNx_VaL7vOSQVeDxBXWckw8TJpU_t6rM',
    appId: '1:437672983587:android:ee93de2fabfa917f330596',
    messagingSenderId: '437672983587',
    projectId: 'pao-app-293f0',
    storageBucket: 'pao-app-293f0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCM2r_15TfIgb0pSAEfcc0B2Eeo0jbnO54',
    appId: '1:437672983587:ios:37fb7574bb758fed330596',
    messagingSenderId: '437672983587',
    projectId: 'pao-app-293f0',
    storageBucket: 'pao-app-293f0.firebasestorage.app',
    iosBundleId: 'com.pao.pao',
  );
}
