import 'package:flutter/material.dart';
import 'legal_document_screen.dart';

class PrivacyPolicyScreen extends StatelessWidget {
  const PrivacyPolicyScreen({super.key});

  @override
  Widget build(BuildContext context) {
    return const LegalDocumentScreen(
      title: 'Privacy Policy',
      lastUpdated: 'September 18, 2026',
      sections: [
        LegalSection(
          '1. Information We Collect',
          'We collect information you provide directly, such as your name, '
              'email address, profile photo, and the listings, requests, or '
              'messages you create. We also collect information generated by '
              'using the app, such as your wishlist, saved location/province, '
              'and app preferences (theme, language).',
        ),
        LegalSection(
          '2. How We Use Your Information',
          'We use your information to operate the app\'s core features: '
              'showing your profile, displaying and matching listings and '
              'requests, enabling chat between users, maintaining your '
              'wishlist, and remembering your settings.',
        ),
        LegalSection(
          '3. Location Information',
          'If you select a location or province, it is used to show you '
              'relevant listings and requests in your area. You can change or '
              'clear this at any time in the app.',
        ),
        LegalSection(
          '4. Sharing With Other Users',
          'Certain information is visible to other users as part of the '
              'app\'s normal operation, such as your profile name and photo '
              'on listings you post, and any messages you send through chat. '
              'We do not sell your personal information to third parties.',
        ),
        LegalSection(
          '5. Data Storage & Security',
          'Your account and app data are stored using Supabase, our backend '
              'service provider, with industry-standard security practices. '
              'While we take reasonable steps to protect your data, no method '
              'of storage or transmission is 100% secure.',
        ),
        LegalSection(
          '6. Your Choices & Rights',
          'You can review and update your profile at any time from Edit '
              'Profile in Settings. You may request deletion of your account '
              'from Settings, which permanently removes your profile, '
              'listings, wishlist, and associated data from our systems.',
        ),
        LegalSection(
          '7. Data Retention',
          'We keep your information for as long as your account is active or '
              'as needed to provide the app\'s features. Once you delete your '
              'account, your personal data is removed except where we are '
              'required to retain it by law.',
        ),
        LegalSection(
          '8. Children\'s Privacy',
          'PAO is not directed at children under 13, and we do not knowingly '
              'collect personal information from children under 13.',
        ),
        LegalSection(
          '9. Changes to This Policy',
          'We may update this Privacy Policy from time to time. We will '
              'reflect the latest revision date at the top of this page.',
        ),
        LegalSection(
          '10. Contact Us',
          'If you have questions about this Privacy Policy or how your data '
              'is handled, please reach out through the Help Center in '
              'Settings.',
        ),
      ],
    );
  }
}
